import type { Product } from './types';

export const initialProducts: Product[] = [
  {
    id: '1',
    name: 'Fresh Oranges',
    description: 'A bag of 10 sweet and juicy navel oranges, perfect for a healthy snack.',
    price: 5.99,
    imageUrl: 'https://placehold.co/600x400/FF9500/FFFFFF',
    'data-ai-hint': 'orange fruit',
    stock: 100,
    labels: ['fruit', 'fresh', 'citrus'],
  },
  {
    id: '2',
    name: 'Artisanal Bread',
    description: 'A freshly baked loaf of sourdough bread with a crispy crust.',
    price: 4.5,
    imageUrl: 'https://placehold.co/600x400/8B4513/FFFFFF',
    'data-ai-hint': 'bread bakery',
    stock: 50,
    labels: ['bakery', 'fresh', 'sourdough'],
  },
  {
    id: '3',
    name: 'Organic Milk',
    description: 'One gallon of certified organic whole milk.',
    price: 3.79,
    imageUrl: 'https://placehold.co/600x400/FFFFFF/000000',
    'data-ai-hint': 'milk carton',
    stock: 75,
    labels: ['dairy', 'organic', 'beverage'],
  },
  {
    id: '4',
    name: 'Free-Range Eggs',
    description: 'A dozen large brown free-range eggs.',
    price: 4.29,
    imageUrl: 'https://placehold.co/600x400/F0E68C/000000',
    'data-ai-hint': 'egg carton',
    stock: 80,
    labels: ['dairy', 'organic', 'protein'],
  },
  {
    id: '5',
    name: 'Avocado',
    description: 'A single ripe Hass avocado, ready to eat.',
    price: 1.99,
    imageUrl: 'https://placehold.co/600x400/556B2F/FFFFFF',
    'data-ai-hint': 'avocado fruit',
    stock: 120,
    labels: ['fruit', 'vegetable', 'healthy'],
  },
  {
    id: '6',
    name: 'Gourmet Coffee Beans',
    description: 'A 12oz bag of whole bean, medium roast arabica coffee.',
    price: 12.99,
    imageUrl: 'https://placehold.co/600x400/6F4E37/FFFFFF',
    'data-ai-hint': 'coffee beans',
    stock: 40,
    labels: ['beverage', 'pantry', 'gourmet'],
  },
];
