export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  sellerId: string;
  stock: number;
  dataAiHint: string;
};

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Luxury Chronograph Watch',
    description: 'A sophisticated timepiece for the modern gentleman. Features a stainless steel case, sapphire crystal glass, and a genuine leather strap.',
    price: 499.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'luxury watch',
    category: 'Accessories',
    sellerId: 'mockSeller',
    stock: 10,
  },
  {
    id: '2',
    name: 'Handcrafted Leather Wallet',
    description: 'Made from full-grain Italian leather, this wallet combines style and functionality. Ages beautifully over time.',
    price: 89.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'leather wallet',
    category: 'Accessories',
    sellerId: 'mockSeller',
    stock: 25,
  },
  {
    id: '3',
    name: 'Organic Beard Oil',
    description: 'Nourish and style your beard with our blend of natural oils. Promotes healthy growth and a soft, manageable beard.',
    price: 24.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'beard oil',
    category: 'Grooming',
    sellerId: 'mockSeller',
    stock: 50,
  },
  {
    id: '4',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in pure audio with these state-of-the-art headphones. Up to 30 hours of battery life.',
    price: 349.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'headphones',
    category: 'Electronics',
    sellerId: 'mockSeller',
    stock: 15,
  },
  {
    id: '5',
    name: 'Classic French Fries',
    description: 'Crispy, golden-brown, and perfectly salted. A timeless favorite for all ages.',
    price: 5.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'french fries',
    category: 'Food & Drink',
    sellerId: 'mockSeller',
    stock: 100,
  },
  {
    id: '6',
    name: 'Minimalist Desk Lamp',
    description: 'A sleek, modern LED desk lamp with adjustable brightness and color temperature. Perfect for any workspace.',
    price: 79.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'desk lamp',
    category: 'Home Goods',
    sellerId: 'mockSeller',
    stock: 20,
  },
  {
    id: '7',
    name: 'Gourmet Coffee Beans',
    description: 'Single-origin Arabica beans from the highlands of Ethiopia. Medium roast with notes of citrus and chocolate.',
    price: 19.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'coffee beans',
    category: 'Food & Drink',
    sellerId: 'mockSeller',
    stock: 40,
  },
  {
    id: '8',
    name: 'Artisan Sourdough Bread',
    description: 'A crusty loaf of naturally leavened sourdough bread, baked fresh daily. Perfect for sandwiches or toast.',
    price: 8.50,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'sourdough bread',
    category: 'Food & Drink',
    sellerId: 'mockSeller',
    stock: 12,
  },
  {
    id: '9',
    name: 'Smart Home Hub',
    description: 'Control all your smart devices from a single, intuitive interface. Compatible with Alexa, Google Assistant, and Apple HomeKit.',
    price: 129.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'smart home',
    category: 'Electronics',
    sellerId: 'mockSeller',
    stock: 22,
  },
  {
    id: '10',
    name: 'Eco-Friendly Yoga Mat',
    description: 'Made from sustainably sourced cork and natural rubber. Non-slip, anti-microbial, and comfortable for your practice.',
    price: 69.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'yoga mat',
    category: 'Sports & Fitness',
    sellerId: 'mockSeller',
    stock: 30,
  },
  {
    id: '11',
    name: 'Insulated Steel Water Bottle',
    description: 'Keep your drinks cold for 24 hours or hot for 12. Durable, leak-proof, and BPA-free. 32 oz capacity.',
    price: 34.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'water bottle',
    category: 'Sports & Fitness',
    sellerId: 'mockSeller',
    stock: 60,
  },
  {
    id: '12',
    name: 'Classic Fountain Pen',
    description: 'Experience the joy of writing with this elegant fountain pen. Features a fine nib for smooth, consistent lines.',
    price: 59.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'fountain pen',
    category: 'Office',
    sellerId: 'mockSeller',
    stock: 18,
  },
  {
    id: '13',
    name: 'Hand-Painted Silk Scarf',
    description: 'A unique, one-of-a-kind silk scarf with a vibrant, abstract design. A wearable piece of art.',
    price: 110.00,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'silk scarf',
    category: 'Accessories',
    sellerId: 'mockSeller',
    stock: 8,
  },
  {
    id: '14',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful, this waterproof speaker delivers rich sound on the go. 15-hour battery life.',
    price: 99.99,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'bluetooth speaker',
    category: 'Electronics',
    sellerId: 'mockSeller',
    stock: 28,
  },
  {
    id: '15',
    name: 'Snake Plant (Sansevieria)',
    description: 'An easy-to-care-for houseplant known for its air-purifying qualities. Comes in a stylish ceramic pot.',
    price: 45.00,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'house plant',
    category: 'Home Goods',
    sellerId: 'mockSeller',
    stock: 15,
  },
  {
    id: '16',
    name: 'Lavender Scented Candle',
    description: 'Made from natural soy wax and infused with pure lavender essential oil for a calming and relaxing aroma.',
    price: 28.00,
    image: 'https://placehold.co/400x400.png',
    dataAiHint: 'scented candle',
    category: 'Home Goods',
    sellerId: 'mockSeller',
    stock: 45,
  },
];
